export const Stuff = {
  baseUrl: "https://api.magicthegathering.io/v1/cards?contains=imageUrl",
  colorChoices: ["white", "blue", "black", "red", "green"],
  cardTypes: [
    " ",
    "Instant",
    "Sorcery",
    "Artifact",
    "Creature",
    "Enchantment",
    "Land",
    "Planeswalker",
  ],
  formatTypes: [
    " ",
    "Brawl",
    "Commander",
    "Historic",
    "Legacy",
    "Modern",
    "Pauper",
    "Pioneer",
    "Standard",
    "Vintage",
  ],
  rarityChoices: [
    "Common",
    "Uncommon",
    "Rare",
    "Mythic",
    "Rare",
    "Special",
    "Basic+Land",
  ],
};
